# If you come from bash you might have to change your $PATH.
export PATH="/usr/local/mysql/bin:/usr/local/sbin:$HOME/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
#export PATH="$HOME/.rbenv/versions:$PATH"
eval "$(rbenv init -)"
# test -d $HOME/.rbenv/ && PATH="$HOME/.rbenv/bin:$PATH"
#
# This formula installs a python2 executable to /usr/local/bin.
# If you wish to have this formula's python executable in your PATH then add
# the following to ~/.zshrc:
#  export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# Path to your oh-my-zsh installation.
export ZSH=/Users/rsmoke/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"

ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git ruby brew osx extract cloudapp bundler)  

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# set local sql password
export DEV_SQLPWD=I9qACl7Jl3xobBZqQM
export TEST_SQLPWD=I9qACl7Jl3xobBZqQM

#export SECRET_KEY_BASE=638008acee976e4f56e59e667f64aae619916bf9fbfa8bedf75dba79cd1a6db9ec7a030e2aadeda4321a7e9a589217fb9191042133c559683318eb52a1add0ac
# You may need to manually set your language environment
# export LANG=en_US.UTF-8
# set tnsname_ora file path
export TNS_ADMIN="$HOME/RailsProjects/tnsname_ora"
export TNS_USER="rmt_lsaadhoc_datawhse1"
export TNS_PWD="lsa8pdq"
export NLS_LANG="AMERICAN_AMERICA.UTF8"
#export GOOGLE_MAPS_JS_API_KEY="AIzaSyA_L4Y4Lf6UCfR8I_4ANI65ki34rmcJev8"
# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

export EDITOR=vim

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
# nvm stuff
export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"

# eval "$(rbenv init -)"  
source $HOME/.zshenv
. `brew --prefix`/etc/profile.d/z.sh

eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
export PATH="/usr/local/opt/php@5.6/bin:$PATH"
export PATH="/usr/local/opt/php@5.6/sbin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/rsmoke/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/rsmoke/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/rsmoke/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/rsmoke/google-cloud-sdk/completion.zsh.inc'; fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Push public key via to address passed as argument.
# ie: sshpub dschmura@humbledaisy.com would result in
# cat ~/.ssh/id_rsa.pub | ssh dschmura@humbledaisy.com "cat >>  ~/.ssh/authorized_keys"
function sshpub() {

    if [ "$1" != "" ] # or better, if [ -n "$1" ]
    then
        cat ~/.ssh/id_rsa.pub | ssh "$1" "cat >>  ~/.ssh/authorized_keys"
    else

    fi
}
fpath=(/usr/local/share/zsh-completions $fpath)
export PATH="/usr/local/opt/php@7.2/bin:$PATH"
export PATH="/usr/local/opt/php@7.2/sbin:$PATH"
export PATH="/usr/local/opt/libxml2/bin:$PATH"
